### ISSUE TITLE
ErrorBoundary for `main`

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara-tsukuyomi#20]
Right now, we have an error boundary in the `renderer` which catches any erros and shows a "Something went wrong" message. We need to implement something similar for the `main` process as well.  So, if some unhandled error occurs in the `main` process, the error boundary catches it, sends it to the rendered which then shows the appropriate dialog box.

**Comment by NikolaGrujicic** [comment]
i will take this

**Comment by apoorvsadana** [comment]
Any update on this @NikolaGrujicic?

**Comment by 0xGavinOwen** [comment]
can i take this?

**Comment by apoorvsadana** [comment]
Sure, assigned to you!
