### ISSUE TITLE
Feat: Disable app running if node is closed

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara-tsukuyomi#24]
Right now, users can run the app regardless of whether the node is running or not. We need to add a configuration parameter to the apps called `requiresRunningNode`. If this is set to true, an error message should be displayed if the user tried to run the app and node is stopped.

Also, if the node is closed, then all the apps which have `requiresRunningNode` enabled, should also be terminated.

**Comment by TedZy829** [comment]
hi, im interested in taking this task

**Comment by apoorvsadana** [comment]
Awesome! Assigned to you @TedZy829

**Comment by apoorvsadana** [comment]
fixed #36
