### ISSUE TITLE
Feat: detect running apps on start

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara-tsukuyomi#25]
Currently, the apps run using Docker containers. So, if someone terminates Tsukuyomi, it's possible that an  app is still running inside a Docker container. This creates an inconsistent state as the next time when Tsukuyomi starts it will assume the app is not running. So if we try to run it, it will throw an error.

We need a way to detect if any app is already running once Tsukuyomi starts. We are already using `dockerode` to interact with Docker containers. We should be able to use `dockerode` for this purpose as well.

**Comment by makluganteng** [comment]
can i just take this

**Comment by apoorvsadana** [comment]
sure thing @makluganteng! assigned to you
