### ISSUE TITLE
Feat: Add a version check on apps

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara-tsukuyomi#26]
Add a new configuration parameter of `nodeVersion` on the apps. If the user is running a different `version` of the node, we should display a warning message.  We should also allow node ranges similar to semantic versioning.

**Comment by makluganteng** [comment]
Can i take this ?

**Comment by TedZy829** [comment]
hi im interested in this one

**Comment by apoorvsadana** [comment]
sure @TedZy829, assigned to you!
