### ISSUE TITLE
Bug: White-Screen on electron app at page load

### ISSUE THREAD

**Issue by Gathin23** [keep-starknet-strange/madara-tsukuyomi#29]
## Expected Behavior

Should run application in the electron app window

## Current Behavior

![Screenshot_20230820_201828](https://github.com/keep-starknet-strange/madara-tsukuyomi/assets/94786511/ca505252-822b-4bbe-890f-ae4f9e0cb7d9)

## Environment

- Node version : v20.5.1
- OS: MacOS, Windows, Linux (Ubuntu,Arch)

**Comment by apoorvsadana** [comment]
fixed with #34
